/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { C4f8RoOSOperationId } from './c4f8-ro-osoperation-id';
/**
 * 
 * @export
 * @interface C4f8RoOSSchemasOperation
 */
export interface C4f8RoOSSchemasOperation {
    /**
     * The RFC 3339 timestamp of when the operation was completed.
     * @type {string}
     * @memberof C4f8RoOSSchemasOperation
     */
    completed?: string;
    /**
     * A message describing the error when the status is `failed`.
     * @type {string}
     * @memberof C4f8RoOSSchemasOperation
     */
    error?: string;
    /**
     * 
     * @type {C4f8RoOSOperationId}
     * @memberof C4f8RoOSSchemasOperation
     */
    id: C4f8RoOSOperationId;
    /**
     * The current status of the asynchronous operation.
     * @type {string}
     * @memberof C4f8RoOSSchemasOperation
     */
    status: C4f8RoOSSchemasOperationStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum C4f8RoOSSchemasOperationStatusEnum {
    Pending = 'pending',
    Running = 'running',
    Completed = 'completed',
    Failed = 'failed'
}

