/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface C4f8RoOSTestConnectionProperties
 */
export interface C4f8RoOSTestConnectionProperties {
    /**
     * Hash version of body.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    bodyHash?: string;
    /**
     * Size of the body in bytes.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    bodySize?: string;
    /**
     * Lists any `cf-cache-status` present.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    cfCacheStatus?: string;
    /**
     * Lists any `cf-ray` present.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    cfRay?: string;
    /**
     * Lists any `cf-wan-error` present.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    cfWanError?: string;
    /**
     * Whether Cloudflare is enabled on the host.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    cloudflare?: string;
    /**
     * Connection closed or open.
     * @type {boolean}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    connectionClose?: boolean;
    /**
     * Amount of seconds that the test lasted.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    elapsedTime?: string;
    /**
     * The hostname queried.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    hostName?: string;
    /**
     * The HTTP status response code.
     * @type {number}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    httpStatus?: number;
    /**
     * HTTP Method used to test the connection.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    method?: string;
    /**
     * What headers are missing.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    missingHeaders?: string;
    /**
     * Protocol used to test the connection.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    protocol?: string;
    /**
     * Indicates if Railgun is enabled on the queried hostname.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    railgun?: string;
    /**
     * HTTP Status code.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    responseStatus?: string;
    /**
     * Url of the domain you can compare the connection to.
     * @type {string}
     * @memberof C4f8RoOSTestConnectionProperties
     */
    url?: string;
}
