/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { C4f8RoOSItemComment } from './c4f8-ro-ositem-comment';
import { C4f8RoOSItemHostname } from './c4f8-ro-ositem-hostname';
import { C4f8RoOSItemIp } from './c4f8-ro-ositem-ip';
import { C4f8RoOSItemRedirect } from './c4f8-ro-ositem-redirect';
import { C4f8RoOSListId } from './c4f8-ro-oslist-id';
/**
 * 
 * @export
 * @interface C4f8RoOSItem
 */
export interface C4f8RoOSItem {
    /**
     * 
     * @type {C4f8RoOSItemComment}
     * @memberof C4f8RoOSItem
     */
    comment?: C4f8RoOSItemComment;
    /**
     * The RFC 3339 timestamp of when the item was created.
     * @type {string}
     * @memberof C4f8RoOSItem
     */
    createdOn?: string;
    /**
     * 
     * @type {C4f8RoOSItemHostname}
     * @memberof C4f8RoOSItem
     */
    hostname?: C4f8RoOSItemHostname;
    /**
     * 
     * @type {C4f8RoOSListId}
     * @memberof C4f8RoOSItem
     */
    id?: C4f8RoOSListId;
    /**
     * 
     * @type {C4f8RoOSItemIp}
     * @memberof C4f8RoOSItem
     */
    ip?: C4f8RoOSItemIp;
    /**
     * The RFC 3339 timestamp of when the item was last modified.
     * @type {string}
     * @memberof C4f8RoOSItem
     */
    modifiedOn?: string;
    /**
     * 
     * @type {C4f8RoOSItemRedirect}
     * @memberof C4f8RoOSItem
     */
    redirect?: C4f8RoOSItemRedirect;
}
