/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MepUEAgcMigrationStep } from './mep-ueagc-migration-step';
import { MepUEAgcMigrationStepRenamedClasses } from './mep-ueagc-migration-step-renamed-classes';
import { MepUEAgcMigrationStepTransferredClasses } from './mep-ueagc-migration-step-transferred-classes';
import { MepUEAgcMigrationTagConditions } from './mep-ueagc-migration-tag-conditions';
/**
 * A single set of migrations to apply.
 * @export
 * @interface MepUEAgcSingleStepMigrations
 */
export interface MepUEAgcSingleStepMigrations extends MepUEAgcMigrationTagConditions {
    /**
     * A list of classes to delete Durable Object namespaces from.
     * @type {Array<string>}
     * @memberof MepUEAgcSingleStepMigrations
     */
    deletedClasses?: Array<string>;
    /**
     * A list of classes to create Durable Object namespaces from.
     * @type {Array<string>}
     * @memberof MepUEAgcSingleStepMigrations
     */
    newClasses?: Array<string>;
    /**
     * A list of classes with Durable Object namespaces that were renamed.
     * @type {Array<MepUEAgcMigrationStepRenamedClasses>}
     * @memberof MepUEAgcSingleStepMigrations
     */
    renamedClasses?: Array<MepUEAgcMigrationStepRenamedClasses>;
    /**
     * A list of transfers for Durable Object namespaces from a different Worker and class to a class defined in this Worker.
     * @type {Array<MepUEAgcMigrationStepTransferredClasses>}
     * @memberof MepUEAgcSingleStepMigrations
     */
    transferredClasses?: Array<MepUEAgcMigrationStepTransferredClasses>;
}
