/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Logging } from './logging';
import { RTW3sz4nRuleAction } from './rtw3sz4n-rule-action';
import { RTW3sz4nRuleCategory } from './rtw3sz4n-rule-category';
import { RTW3sz4nRuleEnabled } from './rtw3sz4n-rule-enabled';
import { RTW3sz4nRuleId } from './rtw3sz4n-rule-id';
/**
 * 
 * @export
 * @interface RTW3sz4nRule
 */
export interface RTW3sz4nRule {
    /**
     * 
     * @type {RTW3sz4nRuleAction}
     * @memberof RTW3sz4nRule
     */
    action?: RTW3sz4nRuleAction;
    /**
     * The parameters configuring the rule's action.
     * @type {any}
     * @memberof RTW3sz4nRule
     */
    actionParameters?: any;
    /**
     * The categories of the rule.
     * @type {Array<RTW3sz4nRuleCategory>}
     * @memberof RTW3sz4nRule
     */
    categories?: Array<RTW3sz4nRuleCategory>;
    /**
     * An informative description of the rule.
     * @type {string}
     * @memberof RTW3sz4nRule
     */
    description?: string;
    /**
     * 
     * @type {RTW3sz4nRuleEnabled & any}
     * @memberof RTW3sz4nRule
     */
    enabled?: RTW3sz4nRuleEnabled & any;
    /**
     * The expression defining which traffic will match the rule.
     * @type {string}
     * @memberof RTW3sz4nRule
     */
    expression?: string;
    /**
     * 
     * @type {RTW3sz4nRuleId}
     * @memberof RTW3sz4nRule
     */
    id?: RTW3sz4nRuleId;
    /**
     * The timestamp of when the rule was last modified.
     * @type {Date}
     * @memberof RTW3sz4nRule
     */
    lastUpdated: Date;
    /**
     * 
     * @type {Logging}
     * @memberof RTW3sz4nRule
     */
    logging?: Logging;
    /**
     * The reference of the rule (the rule ID by default).
     * @type {string}
     * @memberof RTW3sz4nRule
     */
    ref?: string;
    /**
     * The version of the rule.
     * @type {string}
     * @memberof RTW3sz4nRule
     */
    version: string;
}
