/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tm1HTKEcAllowedIdps } from './tm1-htkec-allowed-idps';
import { Tm1HTKEcSchemasAutoRedirectToIdentity } from './tm1-htkec-schemas-auto-redirect-to-identity';
import { Tm1HTKEcSchemasFeatureAppProps } from './tm1-htkec-schemas-feature-app-props';
import { Tm1HTKEcSessionDuration } from './tm1-htkec-session-duration';
/**
 * 
 * @export
 * @interface Tm1HTKEcSchemasWarpProps
 */
export interface Tm1HTKEcSchemasWarpProps extends Tm1HTKEcSchemasFeatureAppProps {
    /**
     * 
     * @type {any}
     * @memberof Tm1HTKEcSchemasWarpProps
     */
    domain?: any;
    /**
     * 
     * @type {any}
     * @memberof Tm1HTKEcSchemasWarpProps
     */
    name?: any;
    /**
     * The application type.
     * @type {string}
     * @memberof Tm1HTKEcSchemasWarpProps
     */
    type?: string;
}
