/* tslint:disable */
/* eslint-disable */
/**
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Configures load shedding policies and percentages for the pool.
 * @export
 * @interface VXFDQCwXLoadShedding
 */
export interface VXFDQCwXLoadShedding {
    /**
     * The percent of traffic to shed from the pool, according to the default policy. Applies to new sessions and traffic without session affinity.
     * @type {number}
     * @memberof VXFDQCwXLoadShedding
     */
    defaultPercent?: number;
    /**
     * The default policy to use when load shedding. A random policy randomly sheds a given percent of requests. A hash policy computes a hash over the CF-Connecting-IP address and sheds all requests originating from a percent of IPs.
     * @type {string}
     * @memberof VXFDQCwXLoadShedding
     */
    defaultPolicy?: VXFDQCwXLoadSheddingDefaultPolicyEnum;
    /**
     * The percent of existing sessions to shed from the pool, according to the session policy.
     * @type {number}
     * @memberof VXFDQCwXLoadShedding
     */
    sessionPercent?: number;
    /**
     * Only the hash policy is supported for existing sessions (to avoid exponential decay).
     * @type {string}
     * @memberof VXFDQCwXLoadShedding
     */
    sessionPolicy?: VXFDQCwXLoadSheddingSessionPolicyEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum VXFDQCwXLoadSheddingDefaultPolicyEnum {
    Random = 'random',
    Hash = 'hash'
}
/**
    * @export
    * @enum {string}
    */
export enum VXFDQCwXLoadSheddingSessionPolicyEnum {
    Hash = 'hash'
}

